-- day2 
use carsales;
select * from car_data;
-- 90. avg price of cars
select round(avg(Price),2)as avg_car_price 
from car_data;

-- 91. total price of cars
select round(sum(Price),2)as total_price_of_cars 
from car_data;


-- 92. min price of  a car
select min(Price)as min_priced_car 
from car_data;

-- 93. max price of a car
select max(Price)as max_priced_car 
from car_data;

-- 94. avg annual income
select round(avg(Annual_income),2)as avg_annual_income
from car_data;

-- 95. max annual income of a customer
select max(Annual_income)as max_annual_income 
from car_data;

-- 96. min annual income
select min(Annual_income)as min_annual_income 
from car_data;

-- 97. total annual income of all customers
select sum(Annual_income)as total_annual_income 
from car_data;

-- 98. avg price of cars
select avg(Price)as avg_male_car_price 
from car_data
where Gender = 'Male';

-- 99. avg price of cars
select avg(Price)as avg_female_car_price 
from car_data
where Gender = 'Female';

-- 100. avg car price of each company
 select Company, round(avg(Price),2)as Companies_avg_carprice 
 from car_data
 group by Company;

-- 101. total revenue generated by each body style
 select Body_style, sum(Price)as total_revenue_by_bodystyle 
 from car_data
 group by Body_style;
 
 -- 102. most expensive car sold by each company
 select Company, max(Price) as most_expensive_price
 from car_data
 group by Company;
 
 -- 103. least expensive car sold by each company
 select Company, min(Price) as least_expensive_price
 from car_data
 group by Company;
 
 -- 104. avg price per body style
 select Body_style, round(avg(Price),2) as avg_price_per_bodystyle
 from car_data
 group by Body_style;
 
 -- 105. max. income customer per region
 select Dealer_Region, max(Annual_income)
 from car_data
 group by Dealer_Region; 
 
 -- 106. min. income customer per region
 select Dealer_Region, min(Annual_income)
 from car_data
 group by Dealer_Region; 
 
  -- 107. avg. income customer per region
 select Dealer_Region, round(avg(Annual_income),2)
 from car_data
 group by Dealer_Region; 
 
 -- 108. min. income customer per region
 select Dealer_Region, min(Price) as min_carprice_perregion
 from car_data
 group by Dealer_Region;
 
  -- 109. min. income customer per region
 select Dealer_Region, max(Price) as max_carprice_perregion
 from car_data
 group by Dealer_Region;
 
 -- 110. which company generates rhe highest total revenue
select Company, sum(Price)as total_revenue
from car_data
group by Company
order by total_revenue desc limit 1; 

 -- 110. which company generates rhe lowest total revenue
select Company, sum(Price)as total_revenue
from car_data
group by Company
order by total_revenue asc limit 1; 

-- 111. which company sells the most expensive car
select Company , max(Price) as most_expensive_pricedcar
from car_data
group by Company
order by most_expensive_pricedcar desc limit 1;
 
-- 112. which region generates the most sales revenue
select Dealer_Region, sum(Price)as total_revenue_per_region
from car_data
group by Dealer_Region
order by total_revenue_per_region desc limit 1; 

-- 113. what is the avg price of a SUV
select round(avg(Price),2)as avg_suv_price from car_data
where Body_style = 'SUV';

-- 114. which company sells the cheapest car on avg
select Company, round(avg(Price),2) as cheapest_avg_price
from car_data
group by Company
order by cheapest_avg_price asc limit 1;

-- 115. which region has the richest avg income customers
select Dealer_Region, round(avg(Annual_income),2) 
as highest_avgincome_perregion
from car_data
group by Dealer_Region
order by highest_avgincome_perregion desc limit 1;

-- 116. which body style generates the highest revenue
select Body_style, sum(Price) 
as highest_Bodystyle_revenue
from car_data
group by Body_style
order by highest_Bodystyle_revenue desc limit 1;

-- 118. change data type of price from varchar to int
alter table car_data modify Price int;

-- 117. difference between highest and lowest price
select max(Price) - min(Price) as price_difference
from car_data;

-- 118. highest priced car model
select model, max(Price) as most_expensive_model
from car_data
group by model
order by most_expensive_model desc limit 1;

-- 119. which body style has the cheapest avg price
select Body_style, round(avg(Price),2)
as cheapest_avg_bodystyle
from car_data
group by Body_style
order by cheapest_avg_bodystyle asc limit 1;

-- 120. total revenue of Capitol KIA
select Dealer_name, sum(Price) as total_revenue
from car_data
where Dealer_Name = 'Capitol KIA';

-- 121. which dealer has the most total revenue
select Dealer_name, sum(Price) as total_revenue
from car_data
group by Dealer_Name
order by total_revenue desc limit 1;

-- 122. which dealer has the least total revenue
select Dealer_name, sum(Price) as total_revenue
from car_data
group by Dealer_Name
order by total_revenue asc limit 1;

-- 123. avg price car for each transmission
select Transmission, round(avg(Price),2) 
as avg_car_price_as_tranmmission
from car_data
group by Transmission;

-- 124. total revenue based on transmissoin type
select Transmission, sum(Price) as 
totalrevenue_as_tranmmission
from car_data
group by Transmission;

-- 125. min. car price as transmission
select Transmission, min(Price) as minprice_as_tranmmission
from car_data
group by Transmission;

-- 126. max. price as transmission
select Transmission, max(Price) as maxprice_as_tranmmission
from car_data
group by Transmission;

-- 127. avg. income of customers for each genders
select Gender, round(avg(Annual_income),2)as avg_income_gender
from car_data
group by Gender;

-- 128. total revenue generated by each car color
select Color, sum(price) as total_revenue_as_color
from car_data
group by color;

-- 129. masx. income customer per company
select Company, max(Annual_income)as Max_annualincome_as_company
from car_data
group by Company;

-- 130. min. income customer per company
select Company, min(Annual_income)as min_annualincome_as_company
from car_data
group by Company;

-- 131. avg price of cars sold in each region
select Dealer_Region, round(avg(Price),2) as avg_price_per_region
from car_data
group by Dealer_Region;

-- 132. total sales revenue for each region and comapny
select Dealer_Region, Company, sum(price) as total_sales_revenue
from car_data
group by Dealer_Region, Company
order by Dealer_Region asc;

-- 133. avg price of cars for each company and body style
select Company, Body_style, round(avg(Price),2) as avg_price
from car_data 
group by Company, Body_style
order by Company asc;

-- 134. max. price of cars sold in each region
select Dealer_Region, max(Annual_income)
as Max_price_as_region
from car_data
group by Dealer_Region;


-- 135. min. price of cars sold in each region
select Dealer_Region, min(Annual_income)
as Min_price_as_region
from car_data
group by Dealer_Region;

-- 136. avg income customers buying auto cars
select Customer_name, round(avg(Annual_income),2)
from car_data 
where Transmission = 'auto'
group by Customer_name;

-- 137. avg income customers buying manual cars
select Customer_name, round(avg(Annual_income),2)
from car_data 
where Transmission = 'manual'
group by Customer_name;

-- 138. total price cars purchased by male customers
select Gender, sum(Price)as total_revenue from car_data
where Gender = 'Male';

-- 139. total price cars purchased by female customers
select Gender, sum(Price)as total_revenue from car_data
where Gender = 'Female';

-- 140. avg car price greater then 50k
select Company, avg(Price)
from car_data
where Price > 50000
group by Company;

-- 141. regions where total revenue exceeds 2.5M
select Dealer_Region, sum(Price)
from car_data
group by Dealer_Region
having sum(Price) > 2500000;

-- 142. body style where above avg price is above overall avg price
select Body_style, avg(Price) 
from car_data
group by Body_style
having avg(Price) > (select avg(Price) from car_data);


-- 143. find company where min car price is above 20k
select Company, min(Price)
from car_data
group by Company
having min(Price) > 20000;


-- 144. company with the highest avg price 
select Company, round(avg(Price),2) as highest_avg_price
from car_data
group by Company
order by highest_avg_price desc limit 1;

-- 145. find body styles where max. price exceeds 80k
select Body_style, max(Price) 
from car_data
where Price > 80000
group by Body_style;

-- 146. findc companies where total revenue is above avg company reveneue
select Company, sum(Price) from car_data
group by Company
having sum(Price) > 
(
	select avg(total_revenue) 
		from (
        select sum(price) as total_revenue
        from car_data
        group by Company
        )as t 

);

-- 147. find regions where min car price is below 20k
select Dealer_Region, min(Price) as min_price_as_region
from car_data
where Price < 20000
group by Dealer_Region;

-- 148. find companies where max. car price exceeds thrice the avg. price
select Company, max(Price) as max_price_twiceavg
from car_data
group by Company
having max(Price) > 3*avg(Price);

-- 149. top 5 companies with highest total revenue
select Company, sum(Price)as total_revenue
from car_data
group by Company
order by total_revenue desc limit 5;

-- 150. top 5 region 
select Dealer_Region, round(avg(Annual_income),2) as avg_income
from car_data
group by Dealer_Region
order by avg_income desc limit 5;

-- 151. body styles of cars where avg. income customers exceeds 100k
select Dealer_Region, round(avg(Annual_income),2) as avg_income
from car_data
group by Dealer_Region
having avg_income > 100000;

-- 152. find companies where total revenue of female customers exceeds male customers
select Company, sum(case when gender = 'Female' then price else 0 end)as female_revenue,
sum(case when gender = 'Male' then price else 0 end) as male_revenue
from car_data
group by Company
having female_revenue > male_revenue;

-- 153. find region where avg car price exceeds 60k
select dealer_region, avg(price) as avg_price
from car_data
group by dealer_region
having avg(price) > 60000;

-- 154. find regions hwre max income exceeds 200k
select dealer_region, max(annual_income) as max_income
from car_data
group by dealer_region
having max(annual_income) > 200000;

-- 155. find companies where min car price is above company avg.  price
select company
from car_data
group by company
having min(price) > avg(price);

-- 156. region with highest revenue from suv
select dealer_region, sum(price) as revenue
from car_data
where body_style = 'suv'
group by dealer_region
order by revenue desc limit 1;

-- bussiness/ hard queries

-- 157. top 3 region with total_revenue
select Dealer_Region, sum(price) as total_revenue
from car_data
group by Dealer_Region
order by total_revenue desc limit 3;

-- 158. Find companies where average price is greater than industry average
select Company, avg(Price) as avg_price
from car_data
group by Company
having avg(Price) > (select avg(Price) from car_data);


-- 160.Find regions where total sales revenue is below average regional revenue 
select Dealer_Region, sum(Price) as total_revenue
from car_data
group by Dealer_Region
having sum(Price) <
(
select avg(region_revenue)
from (
select sum(Price) as region_revenue
from car_data
group by Dealer_Region
)as t
);

-- 161. Find companies where maximum price exceeds 3× minimum price
select Company
from car_data
group by Company
having max(Price) > 3 * min(Price);

-- 162. ind body styles where average price is between 40k and 70k.
select Body_style, avg(Price) as avg_price
from car_data
group by Body_style
having avg(Price) between 40000 and 70000;

-- 163. Find regions where average customer income exceeds national average
-- assume national income of usa is 58900
select Dealer_Region, avg(Annual_income)
from car_data
group by Dealer_Region
having avg(Annual_income) > 58900;

-- 164. Find companies where average income of buyers is highest
select Company, avg(Annual_income) as avg_income
from car_data
group by Company
order by avg_income desc limit 1;

-- 165. Find companies with largest price range (MAX - MIN)
select Company, max(Price) - min(Price) as price_range
from car_data
group by Company
order by price_range desc;

-- 166. Find the body style with highest total revenue
select Body_style, sum(Price) as revenue
from car_data
group by Body_style
order by revenue desc limit 1;

-- 167. Find companies where average price of automatic cars exceeds manual cars
select Company
from car_data
group by Company
having
avg(case when Transmission='auto' then price end) >
avg(case when Transmission='manual' then price end);

-- 168. ind the region generating highest revenue from luxury cars (>70000)
-- assume luxury cars are above 70k
select Dealer_Region, sum(Price) as luxury_revenue
from car_data
where Price > 70000
group by Dealer_Region
order by luxury_revenue desc limit 1;

-- 169. Find companies where maximum price is greater than overall maximum average price.
select Company
from car_data
group by Company
having max(Price) >
(
select max(avg_price)
from (
select avg(Price) as avg_price
from car_data
group by Company
) t
);

-- 170. Find regions where average car price is less than global average.
-- assume global price is 40k
select Dealer_Region, avg(Price)
from car_data
group by Dealer_Region
having avg(Price) < 40000;

-- 171. Find companies where total revenue exceeds 5% of overall revenue
select Company, sum(Price) as total_revenue
from car_data
group by Company
having sum(Price) >
0.05 * (select sum(Price) from car_data);

-- 172. Find body styles where maximum price is greater than twice minimum price.
select Body_style
from car_data
group by Body_style
having max(price) > 2 * min(price);


-- 173. Find regions where highest price car is above 90,000.
select Dealer_Region
from car_data
group by Dealer_Region
having max(Price) > 90000;

-- 174. Find companies where total sales exceed 10 cars and average price > 60,000.
select Company, count(*) as sales, avg(Price)
from car_data
group by Company
having count(*) > 10 and avg(price) > 60000;

-- 175. Find regions where average income and average price are both high
select Dealer_Region, avg(Price), avg(Annual_income)
from car_data
group by Dealer_Region
having avg(price) > (select avg(price) from car_data)
and avg(Annual_income) > (select avg(Annual_income) from car_data);

-- 176. Find the company with highest revenue from automatic cars.
select Company, sum(Price) as total_revenue
from car_data
where Transmission='auto'
group by Company
order by total_revenue desc limit 1;

-- 177. Find the company with highest revenue from manual cars
select Company, sum(Price) as revenue
from car_data
where Transmission='manual'
group by Company
order by revenue desc
limit 1;

-- 178. Find the region where customers spend the most on average.
select Dealer_Region, avg(Price) as avg_spending
from car_data
group by Dealer_Region
order by avg_spending desc limit 1;

-- 179. find the top2 companies generating highest revenue in each region
select Dealer_Region, Company, sum(Price) as total_revenue
from car_data
group by Dealer_Region, Company
order by Dealer_Region, total_revenue desc;

-- 180. Find the most popular body style in each region
select Dealer_Region, Body_style, count(*) as total_sales
from car_data
group by Dealer_Region, Body_style
order by Dealer_Region, total_sales desc;